# 张量运算

In [1]:
import numpy as np

## 逐元素运算

In [2]:
x = np.array([[1.0,-2.0], [-3.0,4.0]])
y = np.array([[-4.0,5.0], [6.0,-7.0]])

print('x = ', x)
print('y = ', y)

x =  [[ 1. -2.]
 [-3.  4.]]
y =  [[-4.  5.]
 [ 6. -7.]]


### native_relu(np.array) == np.maximum(np.array, 0)

In [3]:
"""激活函数relu"""
def native_relu(x):
    assert len(x.shape) == 2
    
    n = x.copy()
    for i in range(n.shape[0]):
        for j in range(n.shape[1]):
            n[i, j] = max(0, n[i, j])
            
    return n

x_relu = native_relu(x)
assert np.array_equal(x_relu, np.maximum(x, 0))
print('native_relu(x) = ', x_relu)

native_relu(x) =  [[1. 0.]
 [0. 4.]]


### native_add(np.array, np.array) == np.add(np.array, np.array) == np.array + np.array

In [4]:
"""矩阵加法"""
def native_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    
    n = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            n[i, j] = x[i, j] + y[i, j]
            
    return n

n = native_add(x, y)
assert np.array_equal(n, np.add(x, y))
assert np.array_equal(n, x + y)
print('native_add(x, y) = ', n)

native_add(x, y) =  [[-3.  3.]
 [ 3. -3.]]


### native_subtract(np.array, np.array) == np.subtract(np.array, np.array) == np.array - np.array

In [5]:
"""矩阵减法"""
def native_subtract(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    
    n = x.copy()
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            n[i, j] = x[i, j] - y[i, j]
            
    return n

n = native_subtract(x, y)
assert np.array_equal(n, np.subtract(x, y))
assert np.array_equal(n, x - y)
print('native_subtract(x, y) = ', n)

native_subtract(x, y) =  [[ 5. -7.]
 [-9. 11.]]


### native_multiply(np.array, np.array) == np.multiply(np.array, np.array) == np.array * np.array

In [6]:
"""矩阵乘法"""
def native_multiply(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    
    n = x.copy()
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            n[i, j] = x[i, j] * y[i, j]
            
    return n

n = native_multiply(x, y)
assert np.array_equal(n, np.multiply(x, y))
assert np.array_equal(n, x * y)
print('native_multiply(x, y) = ', n)

native_multiply(x, y) =  [[ -4. -10.]
 [-18. -28.]]


### native_divide(np.array, np.array) == np.divide(np.array, np.array) == np.array / np.array

In [7]:
"""矩阵除法"""
def native_divide(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    
    n = x.copy()
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            n[i, j] = x[i, j] / y[i, j]
            
    return n

n = native_divide(x, y)
assert np.array_equal(n, np.divide(x, y))
assert np.array_equal(n, x / y)
print('native_divide(x, y) = ', n)

native_divide(x, y) =  [[-0.25       -0.4       ]
 [-0.5        -0.57142857]]


## 张量点积 np.dot(np.array, np.array)

In [16]:
"""向量点积，两个向量的元素个数要求相等，返回值是标量。"""
def native_vertor_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape == y.shape
    
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
        
    return z

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
n = native_vertor_dot(x, y)
assert np.array_equal(n, np.dot(x, y))
print('native_vertor_dot(x, y) = ', n)

native_vertor_dot(x, y) =  32.0


In [28]:
"""矩阵和向量的点积，矩阵的列数和向量的元素数相等，返回值是向量，元素数等于矩阵的行数。"""
def native_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = native_vertor_dot(x[i, :], y)
        
    return z

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 2, 3])
n = native_matrix_vector_dot(x, y)
assert np.array_equal(n, np.dot(x, y))
print('native_matrix_vector_dot(x, y) = ', n)

native_matrix_vector_dot(x, y) =  [14. 32.]


In [32]:
"""矩阵点积，第一个矩阵的列数等于第二个矩阵的行数，返回值是矩阵[第一个矩阵的行数，第二个矩阵的列数]。"""
def native_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            z[i, j] = native_vertor_dot(x[i, :], y[:, j])

    return z

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 2], [3, 4], [5, 6]])
n = native_matrix_dot(x, y)
assert(np.array_equal(n, np.dot(x, y)))
print('native_matrix_dot(x, y) = ', n)

native_matrix_dot(x, y) =  [[22. 28.]
 [49. 64.]]


### 两个张量中有一个ndim大于1，dot运算就不再对称

In [51]:
x = np.array([1, 2])
y = np.array([3, 4])
assert np.dot(x, y) == np.dot(y, x)

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 2], [3, 4], [5, 6]])
assert not np.array_equal(np.dot(x, y), np.dot(y, x))
print(np.dot(x, y).shape, np.dot(y, x).shape)

(2, 2) (3, 3)


## 张量变形

In [58]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
print(x)

x = x.reshape(6, 1)
print(x.shape)
print(x)

x = x.reshape(3, 2)
print(x.shape)
print(x)

# 转置
assert np.array_equal(x.T, np.transpose(x))
x = x.T
print(x.shape)
print(x)

(2, 3)
[[1 2 3]
 [4 5 6]]
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(2, 3)
[[1 3 5]
 [2 4 6]]
